# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a961ebd1fc095daee8655ffbea64fc2ba359f7ea811edfa82c0257ffb1d5664ed41237fe56d601a38fb83e876896d008d7d25760ef5832b21dbf670eb4958c6b

test:
  secret_key_base: 9515bd50fed132f3631a2a7a7477559ada792bab591a56437dcb359c50331c189f81a318d180abaa55931f7329b58378bffeb8f35959cfae8152e0e0875d17a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
